import Head from "next/head";
import Home from "../components/Main/Home";

import Reviews from "../components/Main/Reviews";
import Courses from "../components/Main/Courses";
import Sessions from "@/components/Main/Sessions";
import NeedContact from "@/components/Main/NeedContact";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Home />
        <Reviews />
        <Sessions />
        <Courses />
        <NeedContact />
      </div>
    </>
  );
}
