import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
import Home from "../components/Main/Home";
import Hero from "../components/Main/Hero";
import Reviews from "../components/Main/Reviews";
import Courses from "../components/Main/Courses";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export default function IndexPage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
				></link>
			</Head>
			<Hero />
			<Home />
			<Reviews />
			<Courses />
		</>
	);
}
