import Head from "next/head";
// import Image from "next/image";

import Home from "../components/Main/Home";
import Hero from "../components/Main/Hero";
import Reviews from "../components/Main/Reviews";
import Courses from "../components/Main/Courses";
import Sessions from "@/components/Main/Sessions";
import Footer from "@/components/footer/Footer";
import NeedConctact from "@/components/Main/NeedContact";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


export default function IndexPage() {
    return (
        <>
            <Head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link href="https://fonts.googleapis.com/css2?family=Alkatra:wght@400;700&display=swap" rel="stylesheet" />
                
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
                />
            </Head>
            <Hero />
            <Home />
            <Reviews />
            <Courses />
            <Sessions />
            <NeedConctact />
            <Footer />
        </>
    );
}
